name:Contributors-To-File

on: [push]

jobs:
  contributors_to_file:
    runs-on: ubuntu-latest
    name: Write contributors to file
    steps:
    - name: Checkout repo
      id: checkout
      uses: actions/checkout@v2
    - name: Update contributors
      id: update_contributors
      uses: TheLastProject/contributors-to-file-action@v2
      with:
        file_in_repo: example/index.txt
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Update contributors"
        commit-message: "Update contributors"
